spring.application.name=fintech
spring.profiles.active=${SPRING_PROFILE:postgres}
# Configuración JWT
jwt.secret=${JWT_SECRET:ClaveSecretaPorDefectoParaDesarrolloLocal2026}
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG

python.fastapi.url=${PYTHON_FASTAPI_URL:http://10.0.0.217:8000}