# Conexion Oracle
spring.datasource.url=${DB_URL_CONNECTION}?TNS_ADMIN=${ORACLE_WALLET_PATH}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false